-- Снимок таблицы venues (автогенерация parser-cli export-venues).
-- Строк: 67

INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('perm-12-futov', 'perm', '12 футов', 'billiards', 'Пермь, улица Малкова, 30/2', 'Дзержинский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('perm-adam-i-eva', 'perm', 'Адам и Ева', 'billiards', 'Пермь, КИМ, 93', 'Мотовилихинский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('perm-amaks', 'perm', 'Амакс', 'billiards', 'Пермь, Монастырская улица, 43', 'Ленинский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('perm-ays-karting', 'perm', 'Айс картинг', 'karting', 'Пермь, шоссе Космонавтов, 328/13', NULL, NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('perm-bratya', 'perm', 'Братья', 'billiards', 'Пермь, Кронштадтская улица, 39в стр 2', 'Дзержинский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('perm-costa-rica', 'perm', 'Costa Rica', 'billiards', 'Пермь, улица Борчанинова, 71а', 'Ленинский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('perm-crazy-cart', 'perm', 'Crazy cart', 'karting', 'Пермь, шоссе Космонавтов, 162Б', 'Индустриальный район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('perm-drayv', 'perm', 'Драйв', 'karting', 'Пермь, Встречная улица, 28/1', 'Индустриальный район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('perm-fastfud-room', 'perm', 'Фастфуд room', 'billiards', 'Пермь, Ласьвинская улица, 14', 'Кировский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('perm-kamskaya-dolina', 'perm', 'Камская Долина', 'karting', 'Пермь, улица Спешилова, 90', 'Ленинский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('perm-karton', 'perm', 'KartOn', 'karting', 'Пермь, Восстания, 17 к1', 'Мотовилихинский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('perm-klassik-a', 'perm', 'Классик А', 'billiards', 'Пермь, улица Куйбышева, 37', 'Ленинский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('perm-klevoe-mesto', 'perm', 'Клевое место', 'billiards', 'Пермь, улица Тимирязева, 26', 'Свердловский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('perm-magistrayk', 'perm', 'Магистрайк', 'bowling', 'Пермь, Магистральная улица, 89', 'Кировский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('perm-na-dinamo', 'perm', 'На Динамо', 'billiards', 'Пермь, улица Краснова, 1', 'Свердловский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('perm-niiums-sova', 'perm', 'Нииумс Сова', 'billiards', 'Пермь, улица Ленина, 66Б', 'Ленинский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('perm-olimp', 'perm', 'Олимп', 'billiards', 'Пермь, шоссе Космонавтов, 158а к2', 'Индустриальный район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('perm-papyzdes', 'perm', 'Папыздесь', 'billiards', 'Пермь, улица Белинского, 31', 'Свердловский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('perm-povorot', 'perm', 'Поворот', 'billiards', 'Пермь, Братская улица, 50а', 'Свердловский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('perm-prosto-v-parke', 'perm', 'Просто в Парке', 'billiards', 'Пермь, улица Маршала Рыбалко, 108', 'Кировский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('perm-relax', 'perm', 'Relax', 'billiards', 'Пермь, Вижайская улица, 26/1', 'Свердловский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('perm-resto-bouling', 'perm', 'Ресто-боулинг', 'bowling', 'Пермь, улица Спешилова, 114', 'Ленинский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('perm-ruslan', 'perm', 'Руслан', 'billiards', 'Пермь, Уральская улица, 87', 'Мотовилихинский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('perm-sfera', 'perm', 'Сфера', 'billiards', 'Пермь, Магистральная улица, 89', 'Кировский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('perm-u-trofima', 'perm', 'У Трофима', 'billiards', 'Пермь, Пожарная улица, 14 к3', 'Дзержинский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('perm-va-bank', 'perm', 'Ва-Банк', 'billiards', 'Пермь, улица Куйбышева, 97', 'Свердловский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('perm-white-lanes', 'perm', 'White Lanes', 'bowling', 'Пермь, улица Ленина, 60', 'Ленинский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-23-reys', 'sochi', '23 Рейс', 'karting', 'Пластунка (Сочи городской округ), Бригадный переулок, 1', 'Хостинский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-akopov-zrt', 'sochi', 'Akopov zrt', 'karting', 'Пластунка (Сочи городской округ), Бригадный переулок, 1', 'Хостинский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-akvaloo', 'sochi', 'АкваЛоо', 'bowling', 'Сочи, улица Декабристов, 78 к6', 'Лазаревский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-arena', 'sochi', 'Арена', 'billiards', 'Сочи, улица Гагарина, 78', 'Центральный район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-arnamal', 'sochi', 'Арнамаль', 'billiards', 'Сочи, улица Калараша, 62а', 'Лазаревский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-atrium', 'sochi', 'Атриум', 'billiards', 'Сочи, улица Победы, 166а', 'Лазаревский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-bellagio', 'sochi', 'Bellagio', 'billiards', 'Сочи, Виноградная улица, 184/3', 'Центральный район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-bilyardnaya-o1', 'sochi', 'Бильярдная №1', 'billiards', 'Сочи, улица Ленина, 156', 'Адлерский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-bilyardnyy-klub', 'sochi', 'Бильярдный клуб', 'bowling', 'Сочи, Сочинское шоссе, 28', 'Лазаревский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-bouling-tsentr', 'sochi', 'Боулинг-центр', 'bowling', 'Сочи, улица Пирогова, 10Б', 'Центральный район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-city-stars', 'sochi', 'City Stars', 'bowling', 'Сочи, Транспортная улица, 28', 'Центральный район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-drayvkart', 'sochi', 'Драйвкарт', 'karting', 'Сочи, Демократическая улица, 29', 'Адлерский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-drm-karting', 'sochi', 'ДРМ Картинг', 'karting', 'Сириус (Сириус городской округ), Олимпийский проспект, 15а/1', NULL, NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-gladiator', 'sochi', 'Гладиатор', 'billiards', 'Сочи, улица 20 Горнострелковой Дивизии, 20', 'Хостинский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-glavrak', 'sochi', 'Главрак', 'billiards', 'Сочи, Дивноморская улица, 26/1', 'Хостинский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-gokart-sochi-park', 'sochi', 'Gokart Сочи Парк', 'karting', 'Сириус (Сириус городской округ), Международная улица, 12 киоск', NULL, NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-hali-gali', 'sochi', 'Хали-Гали', 'bowling', 'Эстосадок (Сочи городской округ), улица Горная Карусель, 3', 'Адлерский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-iusupov-team', 'sochi', 'Iusupov Team', 'karting', 'Пластунка (Сочи городской округ), Бригадный переулок, 1', 'Хостинский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-karting-klub', 'sochi', 'Картинг-клуб', 'karting', 'Пластунка (Сочи городской округ), Бригадный переулок, 1', 'Хостинский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-karting-na-krasnoy-polyane', 'sochi', 'Картинг на Красной Поляне', 'karting', 'Эстосадок (Сочи городской округ), Эстонская улица, 19/1а', 'Адлерский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-karting-sport', 'sochi', 'Картинг спорт', 'karting', 'Пластунка (Сочи городской округ), Бригадный переулок, 2а', 'Хостинский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-kartingclub-pro-rivera', 'sochi', 'kartingclub.pro Ривьера', 'karting', 'Сочи, улица Егорова, 1/12', 'Центральный район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-kartingclub-pro-roza-hutor', 'sochi', 'kartingclub.pro Роза Хутор', 'karting', 'Эстосадок (Сочи городской округ), Полянка набережная, 3', 'Адлерский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-korporativnyy-tsentr-sberbanka', 'sochi', 'Корпоративный центр Сбербанка', 'billiards', 'Эстосадок (Сочи городской округ), площадь Сбербанка, 1', 'Адлерский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-lemansmotorsport', 'sochi', 'LemansMotorsport', 'karting', 'Пластунка (Сочи городской округ), Бригадный переулок, 1', 'Хостинский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-malenkaya-sobaka', 'sochi', 'Маленькая Собака', 'billiards', 'Сочи, Курортный проспект, 19/4', 'Центральный район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-mansarda', 'sochi', 'Мансарда', 'billiards', 'Сочи, улица Конституции СССР, 44/3', 'Центральный район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-na-avtodrome', 'sochi', 'На Автодроме', 'karting', 'Сириус (Сириус городской округ), Триумфальная улица, 24Б', NULL, NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-odisseya', 'sochi', 'Одиссея', 'bowling', 'Сочи, Сочинское шоссе, 28', 'Лазаревский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-parad-planet', 'sochi', 'Парад планет', 'bowling', 'Эстосадок (Сочи городской округ), Ачипсинская улица, 12', 'Адлерский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-prokat-detskih-mashinok-samokatov-i-kartingov', 'sochi', 'Прокат детских машинок, самокатов и картингов', 'karting', 'Сочи, улица Ленина, 219а к5', 'Адлерский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-racing-vision', 'sochi', 'Racing vision', 'karting', 'Пластунка (Сочи городской округ), Бригадный переулок, 1', 'Хостинский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-rivera', 'sochi', 'Ривьера', 'karting', 'Сочи, улица Егорова, 1/15', 'Центральный район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-sirius-avtodrom', 'sochi', 'Сириус Автодром', 'karting', 'Сириус (Сириус городской округ), Триумфальная улица, 26/1', NULL, NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-sochi-park', 'sochi', 'Сочи Парк', 'karting', 'Сириус (Сириус городской округ), Олимпийский проспект, 21/2', NULL, NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-talisman', 'sochi', 'Талисман', 'billiards', 'Сочи, Коммунальная улица, 39', 'Хостинский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-toro', 'sochi', 'Торо', 'bowling', 'Сочи, Виноградная улица, 184/3', 'Центральный район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-urartu', 'sochi', 'Urartu', 'billiards', 'Сочи, улица Ленина, 298Б', 'Адлерский район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-vokzal-sochi', 'sochi', 'Вокзал Сочи', 'bowling', 'Сочи, улица Горького, 56', 'Центральный район', NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
INSERT INTO venues (id, city, name, type, address, district, image_url, source, updated_at) VALUES ('sochi-x-ti-sochi-karting', 'sochi', 'X-TI Sochi karting', 'karting', 'Сочи, улица Круизная Гавань, 4а', NULL, NULL, 'twogis', '2026-06-14T12:30:58.790911+00:00')
  ON CONFLICT (id) DO UPDATE SET city = EXCLUDED.city, name = EXCLUDED.name, type = EXCLUDED.type, address = EXCLUDED.address, district = EXCLUDED.district, image_url = EXCLUDED.image_url, source = EXCLUDED.source, updated_at = EXCLUDED.updated_at;
